#version 450
#include "bindless.glsl"
#include "common.h"

#define TRESHOLD 128

layout(local_size_x = 16, local_size_y = 16) in;

PUSH_CONSTANTS(
    uint video_img;
    uint chunk_img;
    uint frame_index;
);

void main()
{
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(g_images_u32[nonuniformEXT(registers.chunk_img)]);
    if (coord.x >= size.x || coord.y >= size.y) return;

    uint luma = imageLoad(g_images_u32[nonuniformEXT(registers.video_img)], coord).r;
    uint cell = imageLoad(g_images_u32[nonuniformEXT(registers.chunk_img)], coord).r;

    if(material(cell) == STONE_VIDEO)
    {
        set_cell(registers.chunk_img, coord, AIR, 0);
    }

    if (luma < TRESHOLD || coord.y == size.y - 1)
    {
        set_cell(registers.chunk_img, coord, STONE_VIDEO, 0); /// always frame index 0 for it to be deterministic.
    }
}